--------------------------------------------------------
--  File created - kedd-május-05-2015   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence PATRON_ID_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "TESTMANO"."PATRON_ID_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 120 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence TRANSACTION_ID_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "TESTMANO"."TRANSACTION_ID_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 120 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table BOOKS
--------------------------------------------------------

  CREATE TABLE "TESTMANO"."BOOKS" 
   (	"BOOK_ID" VARCHAR2(20 BYTE), 
	"TITLE" VARCHAR2(50 BYTE), 
	"AUTHOR_LAST_NAME" VARCHAR2(30 BYTE), 
	"AUTHOR_FIRST_NAME" VARCHAR2(30 BYTE), 
	"RATING" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PATRONS
--------------------------------------------------------

  CREATE TABLE "TESTMANO"."PATRONS" 
   (	"PATRON_ID" NUMBER, 
	"LAST_NAME" VARCHAR2(30 BYTE), 
	"FIRST_NAME" VARCHAR2(30 BYTE), 
	"STREET_ADDRESS" VARCHAR2(50 BYTE), 
	"CITY_STATE_ZIP" VARCHAR2(50 BYTE), 
	"LOCATION" "MDSYS"."SDO_GEOMETRY" 
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table SEQUENCE
--------------------------------------------------------

  CREATE TABLE "TESTMANO"."SEQUENCE" 
   (	"SEQ_NAME" VARCHAR2(50 BYTE), 
	"SEQ_COUNT" NUMBER(38,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TRANSACTIONS
--------------------------------------------------------

  CREATE TABLE "TESTMANO"."TRANSACTIONS" 
   (	"TRANSACTION_ID" NUMBER, 
	"PATRON_ID" NUMBER, 
	"BOOK_ID" VARCHAR2(20 BYTE), 
	"TRANSACTION_DATE" DATE, 
	"TRANSACTION_TYPE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into TESTMANO.BOOKS
SET DEFINE OFF;
Insert into TESTMANO.BOOKS (BOOK_ID,TITLE,AUTHOR_LAST_NAME,AUTHOR_FIRST_NAME,RATING) values ('A1111','Moby Dick','Melville','Herman','10');
Insert into TESTMANO.BOOKS (BOOK_ID,TITLE,AUTHOR_LAST_NAME,AUTHOR_FIRST_NAME,RATING) values ('A2222','Get Rich Really Fast','Scammer','Ima','1');
Insert into TESTMANO.BOOKS (BOOK_ID,TITLE,AUTHOR_LAST_NAME,AUTHOR_FIRST_NAME,RATING) values ('A3333','Finding Inner Peace','Blissford','Serenity',null);
Insert into TESTMANO.BOOKS (BOOK_ID,TITLE,AUTHOR_LAST_NAME,AUTHOR_FIRST_NAME,RATING) values ('A4444','Great Mystery Stories','Whodunit','Rodney','5');
Insert into TESTMANO.BOOKS (BOOK_ID,TITLE,AUTHOR_LAST_NAME,AUTHOR_FIRST_NAME,RATING) values ('A5555','Software Wizardry','Abugov','D.','10');
REM INSERTING into TESTMANO.PATRONS
SET DEFINE OFF;
Insert into TESTMANO.PATRONS (PATRON_ID,LAST_NAME,FIRST_NAME,STREET_ADDRESS,CITY_STATE_ZIP,LOCATION) values ('100','Smith','Jane','123 Main Street','Mytown, MA 01234',null);
Insert into TESTMANO.PATRONS (PATRON_ID,LAST_NAME,FIRST_NAME,STREET_ADDRESS,CITY_STATE_ZIP,LOCATION) values ('101','Murphy','Sam','57 Main Street','Mytown, MA 01234',null);
REM INSERTING into TESTMANO.SEQUENCE
SET DEFINE OFF;
Insert into TESTMANO.SEQUENCE (SEQ_NAME,SEQ_COUNT) values ('SEQ_GEN','0');
REM INSERTING into TESTMANO.TRANSACTIONS
SET DEFINE OFF;
Insert into TESTMANO.TRANSACTIONS (TRANSACTION_ID,PATRON_ID,BOOK_ID,TRANSACTION_DATE,TRANSACTION_TYPE) values ('100','100','A1111',to_date('15-ÁPR.  -14','RR-MON-DD'),'1');
Insert into TESTMANO.TRANSACTIONS (TRANSACTION_ID,PATRON_ID,BOOK_ID,TRANSACTION_DATE,TRANSACTION_TYPE) values ('101','100','A2222',to_date('15-ÁPR.  -14','RR-MON-DD'),'2');
Insert into TESTMANO.TRANSACTIONS (TRANSACTION_ID,PATRON_ID,BOOK_ID,TRANSACTION_DATE,TRANSACTION_TYPE) values ('102','101','A3333',to_date('15-ÁPR.  -14','RR-MON-DD'),'3');
Insert into TESTMANO.TRANSACTIONS (TRANSACTION_ID,PATRON_ID,BOOK_ID,TRANSACTION_DATE,TRANSACTION_TYPE) values ('103','101','A2222',to_date('15-ÁPR.  -14','RR-MON-DD'),'1');
--------------------------------------------------------
--  DDL for Index BOOKS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TESTMANO"."BOOKS_PK" ON "TESTMANO"."BOOKS" ("BOOK_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PATRONS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TESTMANO"."PATRONS_PK" ON "TESTMANO"."PATRONS" ("PATRON_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index TRANSACTIONS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TESTMANO"."TRANSACTIONS_PK" ON "TESTMANO"."TRANSACTIONS" ("TRANSACTION_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index AUTHOR_TITLE_UNIQUE
--------------------------------------------------------

  CREATE UNIQUE INDEX "TESTMANO"."AUTHOR_TITLE_UNIQUE" ON "TESTMANO"."BOOKS" ("AUTHOR_LAST_NAME", "TITLE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C008056
--------------------------------------------------------

  CREATE UNIQUE INDEX "TESTMANO"."SYS_C008056" ON "TESTMANO"."SEQUENCE" ("SEQ_NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table BOOKS
--------------------------------------------------------

  ALTER TABLE "TESTMANO"."BOOKS" ADD CONSTRAINT "AUTHOR_TITLE_UNIQUE" UNIQUE ("AUTHOR_LAST_NAME", "TITLE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "TESTMANO"."BOOKS" ADD CONSTRAINT "BOOKS_PK" PRIMARY KEY ("BOOK_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "TESTMANO"."BOOKS" ADD CONSTRAINT "RATING_1_TO_10" CHECK (rating IS NULL OR
      (rating >= 1 and rating <= 10)) ENABLE;
  ALTER TABLE "TESTMANO"."BOOKS" MODIFY ("AUTHOR_LAST_NAME" CONSTRAINT "LAST_NAME_NOT_NULL" NOT NULL ENABLE);
  ALTER TABLE "TESTMANO"."BOOKS" MODIFY ("TITLE" CONSTRAINT "TITLE_NOT_NULL" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PATRONS
--------------------------------------------------------

  ALTER TABLE "TESTMANO"."PATRONS" ADD CONSTRAINT "PATRONS_PK" PRIMARY KEY ("PATRON_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "TESTMANO"."PATRONS" MODIFY ("LAST_NAME" CONSTRAINT "PATRON_LAST_NOT_NULL" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SEQUENCE
--------------------------------------------------------

  ALTER TABLE "TESTMANO"."SEQUENCE" ADD PRIMARY KEY ("SEQ_NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "TESTMANO"."SEQUENCE" MODIFY ("SEQ_NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TRANSACTIONS
--------------------------------------------------------

  ALTER TABLE "TESTMANO"."TRANSACTIONS" ADD CONSTRAINT "TRANSACTIONS_PK" PRIMARY KEY ("TRANSACTION_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "TESTMANO"."TRANSACTIONS" MODIFY ("TRANSACTION_TYPE" CONSTRAINT "TRAN_TYPE_NOT_NULL" NOT NULL ENABLE);
  ALTER TABLE "TESTMANO"."TRANSACTIONS" MODIFY ("TRANSACTION_DATE" CONSTRAINT "TRAN_DATE_NOT_NULL" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table TRANSACTIONS
--------------------------------------------------------

  ALTER TABLE "TESTMANO"."TRANSACTIONS" ADD CONSTRAINT "FOR_KEY_BOOK_ID" FOREIGN KEY ("BOOK_ID")
	  REFERENCES "TESTMANO"."BOOKS" ("BOOK_ID") ENABLE;
  ALTER TABLE "TESTMANO"."TRANSACTIONS" ADD CONSTRAINT "FOR_KEY_PATRON_ID" FOREIGN KEY ("PATRON_ID")
	  REFERENCES "TESTMANO"."PATRONS" ("PATRON_ID") ENABLE;
